/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_ui;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author earth
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtGoRegister = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Login"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 110, 123));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("LOGIN");

        txtUsername.setText("Username");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.setText("Password");

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Don't have any account? click");

        txtGoRegister.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtGoRegister.setForeground(new java.awt.Color(240, 240, 240));
        txtGoRegister.setText("here");
        txtGoRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGoRegisterMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnLogin.setText("Sign-In");
        btnLogin.setToolTipText("");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGoRegister)
                .addGap(95, 95, 95))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGoRegister))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // แสดงข้อความเเจ้งเตือนเมื่อเข้าสู่ระบบไม่สำเร็จ
    /*public void showFailMessage(){
        if(isFillAllField() == 1){
            JLabel text = new JLabel("กรุณากรอก Password ให้ครบถ้วน");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
        }else if(isFillAllField() == 2){
            JLabel text = new JLabel("กรุณากรอก Username ให้ครบถ้วน");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
        }else if(isFillAllField() == 3){
            JLabel text = new JLabel("กรุณากรอกข้อมูลให้ครบถ้วน");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
        }else if(isFoundUserInDB() == 4){
            JLabel text = new JLabel("ไม่พบผู้ใช้งานอยู่ในระบบ");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
        }else if(isPasswordCorrect() == 5){
            JLabel text = new JLabel("รหัสผ่านไม่ถูกต้อง");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
        }
    }*/
    
    /*public void SubmitLogin(){
        MongoClientURI uri = new MongoClientURI("mongodb://hummel26:hummel26@ds141942.mlab.com:41942/ox");
        MongoClient client = new MongoClient(uri);
        MongoDatabase db = client.getDatabase(uri.getDatabase());
        
        MongoCollection<Document> reg = db.getCollection("Register");
        
        Document user = reg.find(eq("username", txtUsername.getText())).first();
        Document pass = reg.find(eq("password", txtPassword.getText())).first();
        System.out.println(user.toJson());
        System.out.println(pass.toJson());
        System.out.println("มีผู้ใช้งานอยู่ในระบบ");
        System.out.println("รหัสผ่านถูกต้อง");
        System.out.println("ยินดีต้อนรับเข้าสู่ระบบ"); 
        goShowMessage();
    }*/
    
    // เเสดงหน้าต่างหลังจากเข้าสู่ระบบสำเร็จ
    public void goShowMessage(){
        SuccessLogin suc = new SuccessLogin();
        suc.setVisible(true);
        suc.pack();
        suc.setLocationRelativeTo(null);
        suc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }
    
    public static boolean checkUsernameInDB = true;
    
    // ตรวจสอบว่ามี Username บนฐานข้อมูลหรือไม่?
    public void isFoundUserInDB(){
        MongoClientURI uri = new MongoClientURI("mongodb://hummel26:hummel26@ds141942.mlab.com:41942/ox");
        MongoClient client = new MongoClient(uri);
        MongoDatabase db = client.getDatabase(uri.getDatabase());
        
        MongoCollection<Document> reg = db.getCollection("Register");
        try{
            Document myUsername = reg.find(eq("username", txtUsername.getText())).first();
            System.out.println("มีผู้ใช้งานอยู่ในระบบ");
            System.out.println(myUsername.toJson());
            checkUsernameInDB = true;
            isPasswordCorrect();
            /*return 00;*/
        }catch(Exception e){
            System.out.println("ไม่พบผู้ใช้งานอยู่ในระบบ");
            checkUsernameInDB = false;
            JLabel text = new JLabel("ไม่พบผู้ใช้งานอยู่ในระบบ");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
            /*return 4;*/
        }
    }
    
    // ตรวจสอบว่า รหัสผ่าน ถูกต้องหรือไม่ ?
    public void isPasswordCorrect(){
        MongoClientURI uri = new MongoClientURI("mongodb://hummel26:hummel26@ds141942.mlab.com:41942/ox");
        MongoClient client = new MongoClient(uri);
        MongoDatabase db = client.getDatabase(uri.getDatabase());
        
        MongoCollection<Document> reg = db.getCollection("Register");
        
        try{
            Document user = reg.find(eq("username", txtUsername.getText())).first();
            Document pass = reg.find(eq("password", txtPassword.getText())).first();
            System.out.println(user.toJson());
            System.out.println(pass.toJson());
            System.out.println("รหัสผ่านถูกต้อง");
            goShowMessage();
            /*return 000;*/
            /*return true;*/
        }catch(Exception e){
            System.out.println("รหัสผ่านไม่ถูกต้อง");
            JLabel text = new JLabel("รหัสผ่านไม่ถูกต้อง");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
            /*return 5;*/
            /*return false;*/
        }
    }
    
    // ล้างข้อมูลในเเต่ละช่องให้เป็นค่าว่าง
    public void clearText(){
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
    // ตรวจสอบผู้เล่นกรอกข้อมูลครบทุกช่องหรือไม่ ?
    public void isFillAllField(){
        MongoClientURI uri = new MongoClientURI("mongodb://hummel26:hummel26@ds141942.mlab.com:41942/ox");
        MongoClient client = new MongoClient(uri);
        MongoDatabase db = client.getDatabase(uri.getDatabase());
        
        MongoCollection<Document> reg = db.getCollection("Register");
        
        // ผู้เล่นกรอกทั้ง Username เเละ Password < T , T >
        if(!txtUsername.getText().isEmpty()&&!txtPassword.getText().isEmpty()){
            isFoundUserInDB();
            /*return 00;*/
            
        }else
        // ผู้เล่นกรอก Username เเต่ไม่กรอก Password < T , F >
        if(!txtUsername.getText().isEmpty()&&txtPassword.getText().isEmpty()){
            System.out.println("กรุณากรอก Password ให้ครบถ้วน");
            JLabel text = new JLabel("กรุณากรอก Password ให้ครบถ้วน");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
            clearText();
            /*return 1;*/
        }else 
        // ผู้เล่นกรอก Password เเต่ไม่กรอก Username < F , T >
        if(txtUsername.getText().isEmpty()&&!txtPassword.getText().isEmpty()){
            System.out.println("กรุณากรอก Username ให้ครบถ้วน");
            JLabel text = new JLabel("กรุณากรอก Username ให้ครบถ้วน");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
            clearText();
            /*return 2;*/
        }
        // ผู้เล่นไม่ทำการกรอกทั้ง Username เเละ Password < F , F >
        else if(txtUsername.getText().isEmpty()&&txtPassword.getText().isEmpty()){
            System.out.println("กรุณากรอกข้อมูลให้ครบถ้วน");
            JLabel text = new JLabel("กรุณากรอกข้อมูลให้ครบถ้วน");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
            /*return 3;*/
        }   
        /*return 0;*/
    }
    
    private void txtGoRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGoRegisterMouseClicked
        // TODO add your handling code here:
        Register reg = new Register();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtGoRegisterMouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        isFillAllField();  // 00 1 2 3
        /*isFoundUserInDB(); // true false
        isPasswordCorrect(); // true false
        if(isFillAllField() == 1){
            JLabel text = new JLabel("กรุณากรอก Password ให้ครบถ้วน");
            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, text);
            clearText();
        }else{
            if(isFillAllField() == 2){
                JLabel text = new JLabel("กรุณากรอก Username ให้ครบถ้วน");
                text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
                JOptionPane.showMessageDialog(null, text);
                clearText();
            }else{
                if(isFillAllField() == 3){
                    JLabel text = new JLabel("กรุณากรอกข้อมูลให้ครบถ้วน");
                    text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
                    JOptionPane.showMessageDialog(null, text);
                    clearText();
                }else{
                    if(isFillAllField() == 00){
                        if(!checkUsernameInDB){
                            JLabel text = new JLabel("ไม่พบผู้ใช้งานอยู่ในระบบ");
                            text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
                            JOptionPane.showMessageDialog(null, text);
                        }else{
                            if(checkUsernameInDB){
                                if(!isPasswordCorrect()){
                                    JLabel text = new JLabel("รหัสผ่านไม่ถูกต้อง");
                                    text.setFont(new Font("TH Sarabun New", Font.PLAIN, 16));
                                    JOptionPane.showMessageDialog(null, text);
                                }else{
                                    SubmitLogin();
                                }   
                            }
                        }
                    }
                }
            }*/
        }               
        /*showFailMessage();*/
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtGoRegister;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
